### ISSUE TITLE
[Gitalk:/soft/maixpy3/zh/usage/train_AI/train_yolov2.html] 这是用于训练 MaixII-Dock 检测模型的仓库 - Sipeed Wiki

### ISSUE THREAD

**Issue by tangyoubao-name** [sipeed/sipeed_wiki#313]
https://wiki.sipeed.com/soft/maixpy3/zh/usage/train_AI/train_yolov2.html

**Comment by diazGT94** [comment]
Hello, I trained a model with slim yolov2 and could deploy it into the board but I want it to benchmark it with tiny yolo v3. However, when I tried to convert the pytorch weights to onnx I get the following error 

```
input shape: torch.Size([1, 3, 224, 224])
/home/alejo/Documents/MaixPy/v831_yolo/models/tiny_yolo_v3.py:240: TracerWarning: Converting a tensor to a NumPy array might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  all_obj = all_obj.to('cpu').numpy()
/home/alejo/Documents/MaixPy/v831_yolo/models/tiny_yolo_v3.py:241: TracerWarning: Converting a tensor to a NumPy array might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  all_class = all_class.to('cpu').numpy()
/home/alejo/Documents/MaixPy/v831_yolo/models/tiny_yolo_v3.py:242: TracerWarning: Converting a tensor to a NumPy array might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  all_bbox = all_bbox.to('cpu').numpy()
Traceback (most recent call last):
  File "test.py", line 237, in <module>
    torch_to_onnx(net.to("cpu"), input_shape, onnx_out, device="cpu")
  File "/home/alejo/Documents/MaixPy/v831_yolo/convert.py", line 15, in torch_to_onnx
    torch.onnx.export(net, x, out_name, export_params=True, input_names = input_names, output_names=output_names)
  File "/home/alejo/Documents/MaixPy/sipeed/lib/python3.8/site-packages/torch/onnx/__init__.py", line 316, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/alejo/Documents/MaixPy/sipeed/lib/python3.8/site-packages/torch/onnx/utils.py", line 107, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/alejo/Documents/MaixPy/sipeed/lib/python3.8/site-packages/torch/onnx/utils.py", line 724, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/alejo/Documents/MaixPy/sipeed/lib/python3.8/site-packages/torch/onnx/utils.py", line 493, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/alejo/Documents/MaixPy/sipeed/lib/python3.8/site-packages/torch/onnx/utils.py", line 437, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/alejo/Documents/MaixPy/sipeed/lib/python3.8/site-packages/torch/onnx/utils.py", line 388, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/home/alejo/Documents/MaixPy/sipeed/lib/python3.8/site-packages/torch/jit/_trace.py", line 1166, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/alejo/Documents/MaixPy/sipeed/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/alejo/Documents/MaixPy/sipeed/lib/python3.8/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/alejo/Documents/MaixPy/sipeed/lib/python3.8/site-packages/torch/jit/_trace.py", line 121, in wrapper
    out_vars, _ = _flatten(outs)
RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: numpy.ndarray

```

I tried removing the part that converts tensors to numpy arrays but didn't work. Is actually possible to deploy tiny yolo v3 on this board?

**Comment by diazGT94** [comment]
Hi, I succesfully displayed this tutorial with my custom dataset with input images of 224x224. However, the results were not accurate for some small objects so I decided to increase the image size to 320x320, but when I run the script with this image size I get error Segmentation Fault (core dumped), is it possible to deploy models with input size greater than 224x224 on the Maix-II board

**Comment by Kittywyk** [comment]
> @diazGT94
> Hello, I trained a model with slim yolov2 and could deploy it into the board but I want it to benchmark it with tiny yolo v3. However, when I tried to convert the pytorch weights to onnx I get the following error 
> 
> ```
> input shape: torch.Size([1, 3, 224, 224])
> /home/alejo/Documents/MaixPy/v831_yolo/models/tiny_yolo_v3.py:240: TracerWarning: Converting a tensor to a NumPy array might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   all_obj = all_obj.to('cpu').numpy()
> /home/alejo/Documents/MaixPy/v831_yolo/models/tiny_yolo_v3.py:241: TracerWarning: Converting a tensor to a NumPy array might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   all_class = all_class.to('cpu').numpy()
> /home/alejo/Documents/MaixPy/v831_yolo/models/tiny_yolo_v3.py:242: TracerWarning: Converting a tensor to a NumPy array might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   all_bbox = all_bbox.to('cpu').numpy()
> Traceback (most recent call last):
>   File "test.py", line 237, in <module>
>     torch_to_onnx(net.to("cpu"), input_shape, onnx_out, device="cpu")
>   File "/home/alejo/Documents/MaixPy/v831_yolo/convert.py", line 15, in torch_to_onnx
>     torch.onnx.export(net, x, out_name, export_params=True, input_names = input_names, output_names=output_names)
>   File "/home/alejo/Documents/MaixPy/sipeed/lib/python3.8/site-packages/torch/onnx/__init__.py", line 316, in export
>     return utils.export(model, args, f, export_params, verbose, training,
>   File "/home/alejo/Documents/MaixPy/sipeed/lib/python3.8/site-packages/torch/onnx/utils.py", line 107, in export
>     _export(model, args, f, export_params, verbose, training, input_names, output_names,
>   File "/home/alejo/Documents/MaixPy/sipeed/lib/python3.8/site-packages/torch/onnx/utils.py", line 724, in _export
>     _model_to_graph(model, args, verbose, input_names,
>   File "/home/alejo/Documents/MaixPy/sipeed/lib/python3.8/site-packages/torch/onnx/utils.py", line 493, in _model_to_graph
>     graph, params, torch_out, module = _create_jit_graph(model, args)
>   File "/home/alejo/Documents/MaixPy/sipeed/lib/python3.8/site-packages/torch/onnx/utils.py", line 437, in _create_jit_graph
>     graph, torch_out = _trace_and_get_graph_from_model(model, args)
>   File "/home/alejo/Documents/MaixPy/sipeed/lib/python3.8/site-packages/torch/onnx/utils.py", line 388, in _trace_and_get_graph_from_model
>     torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
>   File "/home/alejo/Documents/MaixPy/sipeed/lib/python3.8/site-packages/torch/jit/_trace.py", line 1166, in _get_trace_graph
>     outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
>   File "/home/alejo/Documents/MaixPy/sipeed/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/alejo/Documents/MaixPy/sipeed/lib/python3.8/site-packages/torch/jit/_trace.py", line 127, in forward
>     graph, out = torch._C._create_graph_by_tracing(
>   File "/home/alejo/Documents/MaixPy/sipeed/lib/python3.8/site-packages/torch/jit/_trace.py", line 121, in wrapper
>     out_vars, _ = _flatten(outs)
> RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: numpy.ndarray
> 
> ```
> 
> I tried removing the part that converts tensors to numpy arrays but didn't work. Is actually possible to deploy tiny yolo v3 on this board?

Hi, I also encountered this RuntimeError. Could you please tell me the way you solved it? It would save my life, thanks!!!
