### ISSUE TITLE
[Gitalk:/soft/maixpy/en/others/maixpy_faq.html] MaixPy FAQ - Sipeed Wiki

### ISSUE THREAD

**Issue by yangyang1598** [sipeed/sipeed_wiki#412]
https://wiki.sipeed.com/soft/maixpy/en/others/maixpy_faq.html 

 maixpy  MaixPy FAQ

**Comment by yangyang1598** [comment]
Hello, I develop robot using maixduino
when I using face_detection avility with boot.py, that causing core dump error 
but, I using in maixpy ide. that error wasn't occur.
May I know reason why?

**Comment by desy0305** [comment]
Traceback (most recent call last):
  File "boot.py", line 129, in <module>
  File "boot.py", line 125, in <module>
  File "user.py", line 45, in <module>
  File "user.py", line 19, in start_handler_0
  File "camera.py", line 163, in get_detection_status
  File "camera.py", line 208, in get_detection_result
  File "camera.py", line 53, in snapshot
KeyboardInterrupt: 
MicroPython v0.5.0-395-gcb71b9c42-dirty on 2021-10-21; Sipeed_M1 with kendryte-k210
Type "help()" for more information.
>>> 
classifier __del__

kpu_net __del__

[MaixPy]: soft reboot
[MaixPy] gc heap=0x801c1a60-0x80281a60(786432)
[MaixPy] init end

__  __              _____  __   __  _____   __     __
|  \/  |     /\     |_   _| \ \ / / |  __ \  \ \   / /
| \  / |    /  \      | |    \ V /  | |__) |  \ \_/ /
| |\/| |   / /\ \     | |     > <   |  ___/    \   /
| |  | |  / ____ \   _| |_   / . \  | |         | |
|_|  |_| /_/    \_\ |_____| /_/ \_\ |_|         |_|

Official Site : https://www.tinkergen.com/mark
Docs          : https://www.yuque.com/tinkergen-help-en/mark
MaixPy Wiki   : https://maixpy.sipeed.com

{"board_info": {"WIFI_RX": 7, "ESP32_MOSI": 28, "MIC0_BCK": 18, "MIC0_WS": 19, "WIFI_TX": 6, "ESP32_RST": 8, "ESP32_MISO": 26, "ESP32_SCLK": 27, "PIN0": 4, "LED_G": 12, "ESP32_CS": 25, "PIN1": 5, "PIN3": 22, "PIN4": 23, "LED_B": 14, "PIN5": 24, "ESP32_RDY": 9, "PIN6": 32, "PIN7": 15, "PIN8": 14, "PIN9": 13, "PIN10": 12, "I2S_WS": 33, "I2S_DA": 34, "BOOT_KEY": 16, "MIC0_DATA": 20, "I2S_BCK": 35, "PIN11": 11, "PIN12": 10, "PIN13": 3, "PIN2": 21, "LED_R": 13, "WIFI_EN": 8}, "type": "duino"}
###free gc heap memory : 749 KB

###free sys heap memory: 3388 KB

init i2c:2 freq:100000

[MAIXPY]: find ov2640
[MAIXPY]: find ov sensor
Traceback (most recent call last):
  File "boot.py", line 129, in <module>
  File "boot.py", line 125, in <module>
  File "user.py", line 45, in <module>
  File "user.py", line 19, in start_handler_0
  File "camera.py", line 163, in get_detection_status
  File "camera.py", line 220, in get_detection_resultKeyboardInterrupt: 
MicroPython v0.5.0-395-gcb71b9c42-dirty on 2021-10-21; Sipeed_M1 with kendryte-k210
Type "help()" for more information.
>>> 
>>> 
>>> 
raw REPL; CTRL-B to exit
>OK
False
>
MicroPython v0.5.0-395-gcb71b9c42-dirty on 2021-10-21; Sipeed_M1 with kendryte-k210
Type "help()" for more information.
>>>

**Comment by hiroumi** [comment]
Hi, how can I overclock K219 maix bit?

**Comment by muhammeddincmdx** [comment]
This FAQ documentation is awesome. There are many information and explanations are very successful.I want to say thank you to all contributors.
