### ISSUE TITLE
[Gitalk:/hardware/zh/logic_analyzer/combo8/use_logic_function.html] 作为逻辑分析仪使用 - Sipeed Wiki

### ISSUE THREAD

**Issue by MR-Hear** [sipeed/sipeed_wiki#532]
https://wiki.sipeed.com/hardware/zh/logic_analyzer/combo8/use_logic_function.html

**Comment by xiaoxuqwer** [comment]
逻辑分析仪app希望有中文界面

**Comment by xiaguangbo** [comment]
debian 12 pulseview 有问题，没用起来
```
$ uname -a
Linux debian 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux
```

启动时出现
```
$ sudo ./PulseView-NIGHTLY-x86_64-230811.AppImage 
Translation resource ":/l10n/zh.qm" not found
QT translations for "zh" not found at "/usr/share/qt5/translations" , Qt translations package is probably missing
QT base translations for "zh" not found at "/usr/share/qt5/translations" , Qt translations package is probably missing
srd: ImportError: Failed to load decoder ir_irmp: import by name failed: No module named '_ctypes'
srd: Traceback (most recent call last):
  File "/tmp/.mount_PulseVbKdCFc/usr/share/libsigrokdecode/decoders/ir_irmp/__init__.py", line 25, in <module>
    from .pd import Decoder
  File "/tmp/.mount_PulseVbKdCFc/usr/share/libsigrokdecode/decoders/ir_irmp/pd.py", line 22, in <module>
    from . import irmp_library
  File "/tmp/.mount_PulseVbKdCFc/usr/share/libsigrokdecode/decoders/ir_irmp/irmp_library.py", line 25, in <module>
    import ctypes
  File "/tmp/.mount_PulseVbKdCFc/usr/share/pyshared/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: No module named '_ctypes'
```

点`Run`出现
```
sr: sipeed-slogic-analyzer:     TIMEOUT!
WARNING: Received logic packet with 0 samples.
sr: sipeed-slogic-analyzer:     TIMEOUT!
WARNING: Received logic packet with 0 samples.
sr: sipeed-slogic-analyzer:     TIMEOUT!
WARNING: Received logic packet with 0 samples.
sr: sipeed-slogic-analyzer:     TIMEOUT!
WARNING: Received logic packet with 0 samples.
sr: sipeed-slogic-analyzer:     TIMEOUT!
sr: sipeed-slogic-analyzer:     TIMEOUT!
sr: sipeed-slogic-analyzer:     TIMEOUT!
sr: sipeed-slogic-analyzer:     TIMEOUT!
Acquisition took 0.07 s
```

我的 pyhton 有 _ctypes
```
$ python3
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from _ctypes import Union, Structure, Array
>>> from _ctypes import Union, Structure, Array, abcdefg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'abcdefg' from '_ctypes' (/usr/lib/python3.11/lib-dynload/_ctypes.cpython-311-x86_64-linux-gnu.so)
>>>
```

**Comment by peace0627** [comment]
我下載pulseview開啟後，window系統下沒有找到裝置，scan按下去也沒有任何事情發生

**Comment by Hehaihan20** [comment]
服了,逻辑分析仪完全不能用啊,我设置了输入上拉,逻辑分析仪直接给我下拉了.

**Comment by UFO281** [comment]
scanf for device 有时候扫描不到！！！

**Comment by amigomcu** [comment]
1. Is it possible to integrate with PulseView - sigrok instead of using a specific version.
2. when not find the device then need switch to logic mode again and again?

**Comment by UFO281** [comment]
I just using logic mode,but then have this problem!! I think this is product bug,should fix this bug

________________________________
发件人: amigomcu ***@***.***>
发送时间: 2024年9月3日 9:06
收件人: sipeed/sipeed_wiki ***@***.***>
抄送: 时空自由民 ***@***.***>; Comment ***@***.***>
主题: Re: [sipeed/sipeed_wiki] [Gitalk:/hardware/zh/logic_analyzer/combo8/use_logic_function.html] 作为逻辑分析仪使用 - Sipeed Wiki (Issue #532)


  1.  Is it possible to integrate with PulseView - sigrok instead of using a specific version.
  2.  when not find the device then need switch to logic mode again and again?

―
